local = "{{local_root}}/github.com/longkey1/slago"
remote = "{{remote_root}}/github.com/longkey1/slago"
link_type = "sym"
git_exclude_path = ".git/info/exclude"

[[links]]
  path = "CLAUDE.md"
  type = "sym"
