local = "/Users/m-nagai/work/src/github.com/longkey1/lnkr"
remote = "/Users/m-nagai/work/src/github.com/longkey1/dotfiles/config/lnkr/longkey1/lnkr"
link_type = "sym"
git_exclude_path = ".git/info/exclude"

[[links]]
  path = "AGENTS.md"
  type = "sym"

[[links]]
  path = "CLAUDE.md"
  type = "sym"
