local = "$PWD"
remote = "{{remote_root}}/llmc"
link_type = "sym"
git_exclude_path = ".git/info/exclude"

[[links]]
  path = ".envrc"
  type = "symbolic"

[[links]]
  path = "CLAUDE.md"
  type = "sym"
