golang_url = "https://golang.org"
goroots_dir = "/Users/m-nagai/work/src/github.com/longkey1/dotfiles/config/got/goroots"
temp_dir = "/Users/m-nagai/work/src/github.com/longkey1/dotfiles/config/got/tmp"
versions = [
  "1.25",
  "1.24",
  "1.23",
  "1.22",
  "1.21",
]
