local = "{{local_root}}/github.com/longkey1/llmc"
remote = "{{remote_root}}/github.com/longkey1/llmc"
link_type = "sym"
git_exclude_path = ".git/info/exclude"

[[links]]
  path = ".envrc"
  type = "symbolic"

[[links]]
  path = "CLAUDE.md"
  type = "sym"

# .lnkr.toml is automatically managed as a symbolic link to remote
# [[links]]
# path = ".lnkr.toml"
# type = "sym"
