local = "{{local_root}}/github.com/longkey1/gojira"
remote = "{{remote_root}}/github.com/longkey1/gojira"
link_type = "sym"
git_exclude_path = ".git/info/exclude"
links = []

# .lnkr.toml is automatically managed as a symbolic link to remote
# [[links]]
# path = ".lnkr.toml"
# type = "sym"
